product_image_size: 230
page_size: 15
help_link: "http://www.railstutorial.org/help"
home_link: "http://www.railstutorial.org/"
email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
phone_regex: !ruby/regexp /\A0\d{9}\z/
image_url: "http://gravatar.com/emails"
mailer_from: "noreply@shodadang.com"
maximum_email_length: 255
maximum_name_length: 50
min_password_length: 9
max_rating_star: 5
phone_number: 0123456789
image_format: ["image/jpeg", "image/gif", "image/png"]
max_image_data: 5
digit_160: 160
counter_index: 1
slide_img: "slide-img.jpg"
homepage_delivery: "delivery-truck 1.svg"
homepage_support: "headphones 1.svg"
homepage_shopping: "shopping-bag.svg"
homepage_package: "package.svg"
homepage_popular_category_size: 10
homepage_popular_product_size: 10
homepage_comments: 3
digit_0: 0
digit_1000: 1000
digit_step_discount: 0.01
money_unit: "usd"
money_unit_vnd: "vnd"
money_unit_d: "đ"
counter_index: 1
currency_format: "%n %u"
digit_100: 100
dollar_convert: 0.00004
digit_2 : 2
digit_1 : 1
digit_5 : 5
init_value_add_cart: 1
init_min_add_cart: 1
dicount_percentage_convert: 100
image_size: 200
dd_mm_yyyy: "%d-%m-%Y"
digist_step: 0.1
admin_email: "admin@ecommerce.org"
