product_image_size: 230
page_size: 15
help_link: "http://www.railstutorial.org/help"
home_link: "http://www.railstutorial.org/"
email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
image_url: "http://gravatar.com/emails"
mailer_from: "noreply@shodadang.com"
maximum_email_length: 255
maximum_name_length: 50
min_password_length: 9
max_rating_star: 5
