product_image_size: 230
page_size: 15
help_link: "http://www.railstutorial.org/help"
home_link: "http://www.railstutorial.org/"
email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
image_url: "http://gravatar.com/emails"
mailer_from: "noreply@shodadang.com"
maximum_email_length: 255
maximum_name_length: 50
min_password_length: 9
max_rating_star: 5
phone_number: 0123456789
image_format: ["image/jpeg", "image/gif", "image/png"]
max_image_data: 5
digit_160: 160
counter_index: 1
slide_img: "slide-img.jpg"
homepage_delivery: "delivery-truck 1.svg"
homepage_support: "headphones 1.svg"
homepage_shopping: "shopping-bag.svg"
homepage_package: "package.svg"
homepage_popular_category_size: 10
homepage_popular_product_size: 10
homepage_comments: 3
digit_0: 0
money_unit: "usd"
dollar_convert: 0.042
